// Need to namespace the values because emitter has access to
// the contstants for all objects
var CLASSNAMESConstants = {
  CHANGE: 'CLASSNAMES_CHANGE',
  FETCH: 'CLASSNAMES_FETCH',
  RECEIVE: 'CLASSNAMES_RECEIVE',
  RECEIVE_FAIL: 'CLASSNAMES_RECEIVE_FAIL',
  CREATE: 'CLASSNAMES_CREATE',
  RECEIVE_CREATE: 'CLASSNAMES_RECEIVE_CREATE',
  REVCEIVE_CREATE_FAIL: 'CLASSNAMES_REVCEIVE_CREATE_FAIL'
}
